### ISSUE TITLE
Please upload 1.9.3 release to GNU ELPA

### ISSUE THREAD

**Issue by spwhitton** [jwiegley/emacs-async#100]
This is blocking updating helm in Debian to the 2.9.6 release.

Alternatively Debian could switch back to tracking this GitHub repo -- let me know if I should do that.

**Comment by thierryvolpiatto** [comment]
Sean Whitton <notifications@github.com> writes:

> This is blocking updating helm in Debian to the 2.9.6 release.
>
> Alternatively Debian could switch back to tracking this GitHub repo -- let me know if I should do that.

Please do that, I am not updating anymore ELPA branch.

Thanks.

-- 
Thierry

**Comment by spwhitton** [comment]
Hello,

On Tue, Jun 12 2018, Thierry Volpiatto wrote:

> Sean Whitton <notifications@github.com> writes:
>
>> This is blocking updating helm in Debian to the 2.9.6 release.
>>
>> Alternatively Debian could switch back to tracking this GitHub repo
>> -- let me know if I should do that.
>
> Please do that, I am not updating anymore ELPA branch.

Done.  Thanks.

-- 
Sean Whitton
