### ISSUE TITLE
dired-async-do-delete

### ISSUE THREAD

**Issue by CeleritasCelery** [jwiegley/emacs-async#105]
Just a quick question, why is there no `dired-async-do-delete` function? it seems like it would be one of the most useful functions and I can't help but think there is a reason this was not implemented.

**Comment by thierryvolpiatto** [comment]
Troy Hinckley <notifications@github.com> writes:

> Just a quick question, why is there no dired-async-do-delete function?
> it seems like it would be one of the most useful functions and I can't
> help but think there is a reason this was not implemented.

For some reason it is not implemented in dired-async, but in helm, you
can customize `helm-ff-delete-files-function` to have async deletion in
helm.


--
Thierry
