### ISSUE TITLE
Can't copy large file from some remote machines.

### ISSUE THREAD

**Issue by isolet** [jwiegley/emacs-async#111]
When trying to copy a large remote file to my local directory, `dired-async-do-copy` creates a new buffer call `*emacs*` with content `Lisp expression: File log.txt is large (336.9M), really copy? (y or n) `. I'm not able to answer `y` in this buffer and a character `y` is inserted in to this buffer. The process of this buffer is waiting for reply until I kill it. 

But this did not happen to every remote machine I tested with the same large file size. Some will never prompt for confirmation and copy started automatically. I've tried to set `dired-no-confirm`, but no magic happened.

Small files are always ok. 

Local emacs version: `GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4) of 2019-04-15`

Thanks.

**Comment by thierryvolpiatto** [comment]
isolet <notifications@github.com> writes:

> When trying to copy a large remote file to my local directory,
> dired-async-do-copy creates a new buffer call *emacs* with content
> Lisp expression: File log.txt is large (336.9M), really copy? (y or n)
> . I'm not able to answer y in this buffer and a character y is
> inserted in to this buffer. The process of this buffer is waiting for
> reply until I kill it.
>
> But this did not happen to every remote machine I tested with the same
> large file size. Some will never prompt for confirmation and copy
> started automatically.
>
> Small files are always ok.

Which method are you using to copy?

--
Thierry

**Comment by isolet** [comment]
May I ask what do you mean by 'method'? I setup `dired-async`, use tramp to open a remote `dired` buffer and press `C` on the specific file to copy.

**Comment by thierryvolpiatto** [comment]
isolet <notifications@github.com> writes:

> May I ask what do you mean by 'method'?

ssh? scp?

> I setup dired-async, use tramp to open a remote dired buffer and press
> C on the specific file to copy.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by isolet** [comment]
ssh.

**Comment by thierryvolpiatto** [comment]
isolet <notifications@github.com> writes:

> ssh.

Ah! Try with scp on large files, however you will hit this bug when
trying to copy many files (marked) at once:
https://github.com/emacs-helm/helm/issues/1945

-- 
Thierry

**Comment by isolet** [comment]
Thanks.

**Comment by darkfeline** [comment]
I started experiencing this, why does this happen?

**Comment by thierryvolpiatto** [comment]
darkfeline ***@***.***> writes:

> I started experiencing this, why does this happen?

More infos?

Nothing have changed here since a while, so I guess you maybe have a
tramp bug.

Be sure to use scp method, ssh is unable to copy large files (may even
crash your system as it will quickly goes out of memory).

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by darkfeline** [comment]
Why do you say it's a tramp bug?  If we know it's a tramp bug, is there an upstream report?

I am just trying to understand it since it feels mysterious to me.

The bug you linked in https://github.com/jwiegley/emacs-async/issues/111#issuecomment-485225536 says that scp doesn't work, use ssh instead, and now you say ssh doesn't work, use scp instead?

**Comment by thierryvolpiatto** [comment]
darkfeline ***@***.***> writes:

> Why do you say it's a tramp bug? If we know it's a tramp bug, is there an upstream report?

M-x report-emacs-bug

> I am just trying to understand it since it feels mysterious to me.
>
> The bug you linked in #111 (comment) says that scp doesn't work, use
> ssh instead,

No scp fails to copy more than 3 marked files IIRC (see helm bug 1945), but works fine for a
single large file whereas ssh fails when files are too big.

> and now you say ssh doesn't work, use scp instead?

No please read carefully.

-- 
Thierry
