### ISSUE TITLE
 async-signal (wrong-type-argument stringp nil) ?

### ISSUE THREAD

**Issue by pseudomyne** [jwiegley/emacs-async#121]
Hi. Emacs hangs for a short second every once in a while with :
 
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  signal(wrong-type-argument (stringp nil))
  async-handle-result(#f(compiled-function (events) #<bytecode 0x1426761>) (async-signal (wrong-type-argument stringp nil)) #<buffer *emacs*>)
  async-when-done(#<process emacs> "finished\n")
```
Seems not related to specific commands or tasks.
Any help ? Should I bisect ? 

GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29
Async-20200113.1745
Updated Arch linux.

**Comment by thierryvolpiatto** [comment]
xavier <notifications@github.com> writes:

> Hi. Emacs hangs for a short second every once in a while with :
>
> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>   signal(wrong-type-argument (stringp nil))
>   async-handle-result(#f(compiled-function (events) #<bytecode 0x1426761>) (async-signal (wrong-type-argument stringp nil)) #<buffer *emacs*>)
>   async-when-done(#<process emacs> "finished\n")
>
> Seems not related to specific commands or tasks.
> Any help ?

We need to know what invoked async, looks more like a bug in the
callback function, not async itself.

> Should I bisect ?

Don't think you will find a previous working version as the bug IMO
comes from the callback function which is not part of async.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by pseudomyne** [comment]
Would you tell me what I can do to know what invoked async ? 
(ça fait bizarre de parler en anglais à un français :)

**Comment by thierryvolpiatto** [comment]
xavier <notifications@github.com> writes:

> Would you tell me what I can do to know what invoked async ?

What is the last command you ran before having the error?
Perhaps check in the installed packages which one is using async?

> (ça fait bizarre de parler en anglais à un français :)

Oui mais si on parle français les autres ne comprendront pas ;-)

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by pseudomyne** [comment]
Ok, I've found the culprit : org-wild-notifer. As soon as I disable it, I don't have errors anymore.
Here's how it calls async, in case you'd find anything at first glance : 
```
  (async-start
   (org-wild-notifier--retrieve-events)
   (lambda (events)
     (-each
         (->> events
              (-map 'org-wild-notifier--check-event)
              (-flatten)
              (-uniq))
       'org-wild-notifier--notify))))
```
