### ISSUE TITLE
Cannot byte-compile emacs-async on Emacs 25 and 27

### ISSUE THREAD

**Issue by c4eater** [jwiegley/emacs-async#136]
Hi,
Apparently, emacs-async cannot be byte-compiled under Emacs other than v26. I'm using the git upstream.

Under Emacs 27, "make" breaks on the autoloads target:
`Wrong type argument: stringp, nil`

Under Emacs 26, "make" works fine.

Under Emacs 25, "make" generates the autoloads, but subsequent byte-compilation emits a bunch of errors:
`Error: Cannot open load file: cl-lib`

Thanks

**Comment by c4eater** [comment]
Apologies, I didn't sync up with git master. This was fixed by 14f48de.

**Comment by thierryvolpiatto** [comment]
c4eater <notifications@github.com> writes:

> Hi,
> Apparently, emacs-async cannot be byte-compiled under Emacs other than v26. I'm using the git upstream.
>
> Under Emacs 27, "make" breaks on the autoloads target:
> Wrong type argument: stringp, nil

Can't reproduce, make works fine on emacs-27.

> Under Emacs 26, "make" works fine.
>
> Under Emacs 25, "make" generates the autoloads, but subsequent byte-compilation emits a bunch of errors:
> Error: Cannot open load file: cl-lib

I have no more emacs-25 to try so I can't tell, but well emacs-25 is now
far behind us...

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
c4eater <notifications@github.com> writes:

> Hi,
> Apparently, emacs-async cannot be byte-compiled under Emacs other than
> v26. I'm using the git upstream.

Which git upstream?

An issue on Makefile for emacs-27 have been fixed on github by 14f48de
commit, is it the one you are using?

>
>
> Under Emacs 27, "make" breaks on the autoloads target:
> Wrong type argument: stringp, nil
>
> Under Emacs 26, "make" works fine.
>
> Under Emacs 25, "make" generates the autoloads, but subsequent byte-compilation emits a bunch of errors:
> Error: Cannot open load file: cl-lib
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry
