### ISSUE TITLE
rename or copy fails without any error message 

### ISSUE THREAD

**Issue by dinojr** [jwiegley/emacs-async#141]
Recently, each async move or copy command in dired fails (the original file is not modified) without any error message.

I'm running GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.25, cairo version 1.16.0) of 2021-04-22, using async-20210117.718 from elpa
I tried in emacs -Q with
(package-initialize)
(autoload 'dired-async-mode "dired-async.el" nil t)
(dired-async-mode 1)

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles ***@***.***> writes:

> Recently, each async move or copy command in dired fails (the original file is not modified) without any error message.
>
> I'm running GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+
> Version 3.24.25, cairo version 1.16.0) of 2021-04-22

Are you using native-compile branch ?

> , using async-20210117.718 from elpa

Elpa or Melpa?


-- 
Thierry

**Comment by dinojr** [comment]
> Julien Cubizolles ***@***.***> writes:
> Recently, each async move or copy command in dired fails (the original file is not modified) without any error message. I'm running GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.25, cairo version 1.16.0) of 2021-04-22
> Are you using native-compile branch ?
no, according to
`(if (and (fboundp 'native-comp-available-p)
       (native-comp-available-p))
  (message "Native compilation is available")
(message "Native complation is *not* available"))`

> , using async-20210117.718 from elpa
> Elpa or Melpa?

Actually I don't really know since both are configured for package use. However, I reinstalled from elpa and the problem is still here.

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles ***@***.***> writes:

>     Julien Cubizolles @.***> writes:
>     Recently, each async move or copy command in dired fails (the original file is not modified) without any error message. I'm running GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu,
>     GTK+ Version 3.24.25, cairo version 1.16.0) of 2021-04-22
>     Are you using native-compile branch ?
>     no, according to
>     (if (and (fboundp 'native-comp-available-p) (native-comp-available-p)) (message "Native compilation is available") (message "Native complation is *not* available"))

Ok, I will have to build emacs-28 and see what is going on, it is
working fine on emacs-28 compiled with native-comp (need a little
tweak in installation though).
And of course working fine on 27.2 and before.

>     , using async-20210117.718 from elpa
>     Elpa or Melpa?
>    
> Actually I don't really know since both are configured for package
> use. However, I reinstalled from elpa and the problem is still here.

Be sure to always use Melpa, Elpa is outdated.

    (setq package-pinned-packages '((async . "melpa")))


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Update, it is no more working with last emacs-28 compiled with native-comp.

**Comment by dinojr** [comment]
yep, just compiled it with native-comp here and I can confirm it's not working.

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles ***@***.***> writes:

> yep, just compiled it with native-comp here and I can confirm it's not working.

Yes, it is in discussion see emacs bug#46790

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Should work now, it have been fixed in emacs master see bug#46790.

Thanks.

**Comment by thierryvolpiatto** [comment]
And also by commit 943a75c6a5375de132c32914e0fd0a0d368931f2

**Comment by dinojr** [comment]
Thanks, it's working fine now.
