### ISSUE TITLE
Add optional ON-FAILURE-FUNC argument to async-start

### ISSUE THREAD

**Issue by KaiHa** [jwiegley/emacs-async#152]
First of all thanks, for this awesome package.  I regularly use _async_ together with _ob-async_ and sometimes encounter the case where my START-FUNC code calls _signal_ or _error_.  The only way to handle signals seems to be to use async-wait, but that does not really fit well with my use case.  Therefore my question, is there already a better way to handle signals that is built into async and that I am not aware of?

If not, would it be a good idea to make START-FUNC of _async-start_ an optional cons `'(START-FUNC . ON-FAILURE-FUNC)`, with ON-FAILURE-FUNC being called in case of a signal?

If yes, I could give it a stab.

**Comment by thierryvolpiatto** [comment]
Kai ***@***.***> writes:

> First of all thanks, for this awesome package. I regularly use async
> together with ob-async and sometimes encounter the case where my
> START-FUNC code calls signal or error. The only way to handle signals
> seems to be to use async-wait, but that does not really fit well with
> my use case. Therefore my question, is there already a better way to
> handle signals that is built into async and that I am not aware of?

It works quite well to catch error from START-FUNC and write it to a
temp file and read the file from the CALLBACK, see
`async-byte-compile-file` for example.

-- 
Thierry

**Comment by KaiHa** [comment]
> It works quite well to catch error from START-FUNC and write it to a temp file and read the file from the CALLBACK, see `async-byte-compile-file` for example.

Thanks, you are right.  That is indeed an obvious and easier solution to my problem.
