### ISSUE TITLE
Bump version for GNU ELPA

### ISSUE THREAD

**Issue by skangas** [jwiegley/emacs-async#155]
The version of emacs-async on GNU ELPA is over a year old: https://elpa.gnu.org/packages/async.html

It would be nice if a new version could be released with the latest changes. Thanks!

**Comment by gusbrs** [comment]
It seems the version has been bumped. But is the tag [v3.8.8](https://github.com/jwiegley/emacs-async/releases/tag/v3.8.8) really correct/intended?

**Comment by thierryvolpiatto** [comment]
Gustavo Barros ***@***.***> writes:

> It seems the version has been bumped. But is the tag v3.8.8 really correct/intended?

No the tag v3.8.8 was for Helm and wrongly ran git tag from the wrong
directory.
Thanks to catch this the tag has been removed.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by skangas** [comment]
The new version is now on GNU ELPA, so I'm closing this. Thanks!

**Comment by gusbrs** [comment]
> No the tag v3.8.8 was for Helm and wrongly ran git tag from the wrong directory. Thanks to catch this the tag has been removed.

Thanks @thierryvolpiatto . But I think there's still some trouble in sight in this regard. MELPA Stable is still offering at this moment v3.8.8 (https://stable.melpa.org/#/async). I guess this means that the tag removal does not propagate with the MELPA recipe, I'd expect it to have been done by now if it did.

Of course, the trouble is that anyone who does upgrade to v3.8.8 from MELPA Stable without noticing will remain a looong time without receiving further updates. And the longer this stays in their server, the more people will be affected (even if MELPA Stable is less popular than the main MELPA).

**Comment by thierryvolpiatto** [comment]
Thanks, I opened a new issue on Melpa.

**Comment by gusbrs** [comment]
Thank you!

**Comment by thierryvolpiatto** [comment]
Stefan Kangas ***@***.***> writes:

> The version of emacs-async on GNU ELPA is over a year old: https://elpa.gnu.org/packages/async.html
>
> It would be nice if a new version could be released with the latest changes. Thanks!

Done, thanks.



-- 
Thierry
