### ISSUE TITLE
Keep Getting errors on all Compilations at Server Startup

### ISSUE THREAD

**Issue by stef204** [jwiegley/emacs-async#160]
Emacs 28.2
async-20221103.638
Linux

I am not familiar with `async` but `helm` and `helm-core` have pulled it in as a dependency.
Every time I start `emacs-server` `async` starts compiling and gives off a huge number of lines as so:

````
x86_64-pc-linux-gnu-gcc-12.2.0: fatal error: cannot execute ‘as’: execvp: No such file or directory
compilation terminated.
uncompressing mailabbrev.el.gz...
uncompressing mailabbrev.el.gz...done
Compiling /usr/share/emacs/28.2/lisp/gnus/gnus-util.el.gz...
uncompressing gnus-util.el.gz...
uncompressing gnus-util.el.gz...done
x86_64-pc-linux-gnu-gcc-12.2.0: fatal error: cannot execute ‘as’: execvp: No such file or directory
compilation terminated.
x86_64-pc-linux-gnu-gcc-12.2.0: fatal error: cannot execute ‘as’: execvp: No such file or directory
compilation terminated.
Compiling /usr/share/emacs/28.2/lisp/epa.el.gz...
uncompressing epa.el.gz...
uncompressing epa.el.gz...done
Compiling /usr/share/emacs/28.2/lisp/mail/rmail.el.gz...
uncompressing rmail.el.gz...
uncompressing rmail.el.gz...done
x86_64-pc-linux-gnu-gcc-12.2.0: fatal error: cannot execute ‘as’: execvp: No such file or directory
compilation terminated.
x86_64-pc-linux-gnu-gcc-12.2.0: fatal error: cannot execute ‘as’: execvp: No such file or directory
compilation terminated.
````

And many more lines.

What is going on here?  And how to fix?

Why is `async` needed by `helm` in the first place...?

**Comment by thierryvolpiatto** [comment]
stef204 ***@***.***> writes:

> Emacs 28.2
> async-20221103.638
> Linux
>
> I am not familiar with async but helm and helm-core have pulled it in
> as a dependency.

Yes and it is not new, we never had problems with this.

> 
> Every time I start emacs-server async starts compiling and gives off a
> huge number of lines as so:

What is emacs-server?
Why make you think emacs-async (and/or helm) is/are involved here?

> What is going on here? And how to fix?

Not enough infos, we don't know what you are doing exactly.

> Why is async needed by helm in the first place...?

It is needed, and as said above this is not new.

-- 
Thierry

**Comment by stef204** [comment]
What do you need from me to help me debug/troubleshoot?
Also could it be due to the latest gcc version (12.2.0)? Not every linux distro uses the latest version.

**Comment by thierryvolpiatto** [comment]
stef204 ***@***.***> writes:

> What do you need from me to help me debug/troubleshoot?

We don't know what is happenning and when, please describe step by step
what you are doing with Emacs.

> Also could it be due to the latest gcc version (12.2.0)?

Do you mean this happen when you are compiling Emacs?

> Not every linux distro uses the latest version.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by stef204** [comment]
No, this happens when I start emacs-server + emacs client.  `async` I believe tries to compile packages and fails with the error messages above.
I have rebooted now and did not run into it for the first time today.  So it may have resolved itself. 
I will wait a couple of days and if the issue does not come back, I will close this.  If it shows up again, I will describe it in detail so we can troubleshoot.
Thanks for patience.
