### ISSUE TITLE
invalid-read-syntax when installing packages with async-bytecomp set

### ISSUE THREAD

**Issue by glyph** [jwiegley/emacs-async#169]
It looks to me like #153 has regressed.

My package-installation routine is a bit weird (I have a script that updates everything in batch mode in a pristine Emacs environment every time), so I don't know if my backtraces would be useful, but they're big piles of errors related to packages with warnings, that start happening immediately after `async` is installed, if I don't `(setf async-bytecomp-allowed-packages nil)` first.

The last version where upgrading worked smoothly was `async-20230216.559`.  The version that is now broken is `20230309.1248`. I am running

**Comment by basil-conto** [comment]
Copying in @Fuco1, who's made some changes since the last working version that you report.

**Comment by Fuco1** [comment]
I can recreate this, somewhat, but it gives me different read error.  I'll look into it.

**Comment by Fuco1** [comment]
I have a fix which works but I'm trying to make it extra robust for the future.  I've added some CI builds on my fork https://github.com/Fuco1/emacs-async/actions/runs/4400041297/jobs/7705001460 and stuff randomly does not work on windows and mac os... so I'd also like to fix that.  I seem to see where the problems are.

Tomorrow I'll hopefully finish it, now it's time to go sleep :/
