### ISSUE TITLE
Async bytecomp broken on Emacs master: `Invalid read syntax: "#"`

### ISSUE THREAD

**Issue by Stebalien** [jwiegley/emacs-async#188]
On Emacs master, invoking `async-byte-compile-file` fails with:

```
error in process sentinel: async-when-done: Invalid read syntax: "#"
error in process sentinel: Invalid read syntax: "#"
```

I've narrowed this down to the recent obarray changes (https://github.com/emacs-mirror/emacs/commit/6803b70c1972bc82f7dc1f1d6bbb2a60b6f40367 and the following commit).

**Comment by thierryvolpiatto** [comment]
Steven Allen ***@***.***> writes:

> On Emacs master, invoking async-byte-compile-file fails with:
>
> error in process sentinel: async-when-done: Invalid read syntax: "#"
> error in process sentinel: Invalid read syntax: "#"

I can't reproduce here, with a build of yesterday night.

> I've narrowed this down to the recent obarray changes ***@***.*** and the following commit).

This commit doesn't modify code, only docs AFAICT.

-- 
Thierry

**Comment by Stebalien** [comment]
Ah, sorry, the previous commits: 462d8ba813e07a25b71f5c1b38810a29e21f784c, 3ea77c735de975ebda707e0e1e8bb5e0adad2bf5.

I tested by building:

- 6a182658a533acab94d8fa0aec3e2b7a4f7d6a93 (works)
- 6803b70c1972bc82f7dc1f1d6bbb2a60b6f40367 (doesn't work)

**Comment by thierryvolpiatto** [comment]
I see these commits:

![Capture d’écran_2024-02-27_20-51-15](https://github.com/jwiegley/emacs-async/assets/1533939/1dfdfb69-0b65-4c27-bd17-6d59a798263e)

My build has these commits but I still can't reproduce, perhaps you could provide the file you are trying to compile?

**Comment by unhammer** [comment]
I'm getting this error from `async-smtpmail-send-it` after upgrading to [emacs 30.0.91](https://github.com/emacs-mirror/emacs/commit/9a1c76bf7ff49d886cc8e1a3f360d71e62544802). async-1.9.9 from elpa, recompiled after upgrading emacs
