### ISSUE TITLE
Shouldn't print-level/length be let bound to nil?

### ISSUE THREAD

**Issue by Malabarba** [jwiegley/emacs-async#48]
Looking at the source code of `async--insert-sexp`, I see it uses `prin1`.
I think there should be a let form around that expression to prevent truncation of the printed data, like: 

    (let (print-level print-length)
      (prin1 sexp (current-buffer)))

I've had users reporting errors involving ellipses in the background function.

(Namely bruce-connor/paradox#37 and bruce-connor/paradox#50)

**Comment by thierryvolpiatto** [comment]
Done thanks.
