### ISSUE TITLE
cannot byte-compile file synchronically 

### ISSUE THREAD

**Issue by bixuanzju** [jwiegley/emacs-async#49]
I have the following code in my emacs setup, which will regenerate `.el` file after saving:
```el
  (defun my/init-hook ()
    "If the current buffer is 'emacs-init.org' the code-blocks
are tangled, and the tangled file is compiled."
    (when (equal (buffer-file-name) my-org-file)
      (async-start
       `(lambda ()
          (require 'org)
          (org-babel-tangle-file ,my-org-file)
          (byte-compile-file ,my-init-file))
       (lambda (result)
         (message "Tangled file compiled.")))))
  (add-hook 'after-save-hook 'my/init-hook))
```
The problem is, it never byte-compiles the generated file even though I have `(byte-compile-file ,my-init-file)` in the code.

**Comment by jwiegley** [comment]
What makes you think this is a problem with `emacs-async`?  Have you tried doing other things in your async handler, like writing a debug string to a file?

**Comment by bixuanzju** [comment]
@jwiegley My bad. I have some problems in my setup.
