### ISSUE TITLE
using auth-sources from auth-password-store does not work

### ISSUE THREAD

**Issue by jagguli** [jwiegley/emacs-async#53]
https://github.com/DamienCassou/auth-password-store

``` elisp
(require 'auth-password-store)
(auth-pass-enable)
(setq send-mail-function 'async-smtpmail-send-it
      message-send-mail-function 'async-smtpmail-send-it)
```

**Comment by thierryvolpiatto** [comment]
Steven <notifications@github.com> writes:

> https://github.com/DamienCassou/auth-password-store

I have no idea how this is working.
If you want something to be fixed please develop and try to provide
infos on what is missing to make it working.

If regular smtpmail-send-it is working with your package, probably you
can pass these infos through the `async-smtpmail-before-send-hook'.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by jagguli** [comment]
I tried to require the module in the before send hook, but that failed to find the module (is there any reason for this related to async?). Im not yet very fluent in elisp/lisp but im getting there

**Comment by seanfarley** [comment]
Strange. I just ran into this (because I just switched to `pass`). I tried debugging but can't get any breakpoints to hit (presumably due to the asynchronous part).

**Comment by seanfarley** [comment]
With @DamienCassou's help, I was able to figure this out. `auth-source-pass-enable` needs to be called in the `async-smtpmail-before-send-hook` like so:

```lisp
(add-hook 'async-smtpmail-before-send-hook #'auth-source-pass-enable)
```

So, I believe this issue can be closed now.

**Comment by jwiegley** [comment]
Thanks!
