### ISSUE TITLE
Add epg-* to the environment in smtpmail-async

### ISSUE THREAD

**Issue by orki** [jwiegley/emacs-async#54]
Right now, I have to resort to a lambda added to async-smtpmail-before-send-hook to set `epg-gpg-program` correctly. Would you consider adding epg* variables as part of the list of injected variables in smtpmail-async?

**Comment by thierryvolpiatto** [comment]
orki <notifications@github.com> writes:

> Would you consider adding epg* variables as part of the list of
> injected variables in smtpmail-async?

Done.

-- 
Thierry
https://emacs-helm.github.io/helm/
