### ISSUE TITLE
Renaming files doesn't offer to reload buffers

### ISSUE THREAD

**Issue by jgarvin** [jwiegley/emacs-async#56]
Without emacs-async, if you rename a file in dired emacs will offer to change any buffers open showing the file to instead show the new one. With emacs-async you are not given the option, even after the operation completes. To reproduce:

1. open a file X
2. open file X's folder in dired
3. Press 'R' on the file to rename, give a new name
4. Observe the file X buffer is still open on the old name

**Comment by thierryvolpiatto** [comment]
jgarvin <notifications@github.com> writes:

> Without emacs-async, if you rename a file in dired emacs will offer to
> change any buffers open showing the file to instead show the new
> one. With emacs-async you are not given the option, even after the
> operation completes. To reproduce:
>
>  1. open a file X
>  2. open file X's folder in dired
>  3. Press 'R' on the file to rename, give a new name
>  4. Observe the file X buffer is still open on the old name

Thanks for the recipe, should be fixed now, let me know if something
wrong, I fixed it very fast this morning ...

-- 
Thierry
https://emacs-helm.github.io/helm/
