### ISSUE TITLE
async-bytecomp fail whis package from archive that has been removed.

### ISSUE THREAD

**Issue by vanicat** [jwiegley/emacs-async#58]
doing something like
- adding melpa to package-archives
- installing a package only available there (say helm)
- removing melpa from package-archives

will make async-bytecomp fail to install any new package from other archives, even if such a package is not related to helm or async. It seem that async-bytecomp assume that any installed package is still in `package-archive-contents`, when this could become false.

may be replacing the `package-archive-contents` from `async-bytecomp--get-package-deps` by

     (append package-alist package-archive-contents)

will protect again such problem.

**Comment by thierryvolpiatto** [comment]
Rémi Vanicat <notifications@github.com> writes:

> doing something like
>
>   * adding melpa to package-archives
>   * installing a package only available there (say helm)
>   * removing melpa from package-archives
>
> will make async-bytecomp fail to install any new package from other archives, even if such a package is not related to helm or async It seem that async-bytecomp
> assume that any installed package is still in package-archive-contents, when this could become false
>
> may be replacing the package-archive-contents from async-bytecomp--get-package-deps by
>
>  (append package-alist package-archive-contents)
>
> will protect again such problem

I made a different fix, let me know if it is working for you.

Thanks.

-- 
Thierry

**Comment by jwiegley** [comment]
@thierryvolpiatto Forgot to tell you directly: `async` and now in GNU ELPA, and development on async should occur directly there.  We can mirror here on GitHub to receive pull requests and bug reports, but ELPA should now be considered the "canonical master", since it is already receiving bug fixes from the core developers there.

**Comment by vanicat** [comment]
I can confirm that your fix work for me.

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> @thierryvolpiatto Forgot to tell you directly: async and now in GNU
> ELPA, and development on async should occur directly there.

I have no more write access there... 

-- 
Thierry

**Comment by jwiegley** [comment]
Ok, then just keep working here and I'll merge into ELPA when you make releases or tell me to.

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> Ok, then just keep working here and I'll merge into ELPA when you make
> releases or tell me to.

Great, thanks.  How the merges from ELPA will happen on github ?

-- 
Thierry

**Comment by jwiegley** [comment]
Going forward, I'll use git-subtree to track github emacs-async as if it were a subtree within the ELPA repository. I should have done that today, but in the interests of being expedient, I just did it manually and copied the changes back and forth.

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> Going forward, I'll use git-subtree to track github emacs-async as if
> it were a subtree within the ELPA repository. I should have done that
> today, but in the interests of being expedient, I just did it manually
> and copied the changes back and forth.

Ok, thanks for the info.

-- 
Thierry
