### ISSUE TITLE
Please upload emacs-async version 1.7 to GNU ELPA

### ISSUE THREAD

**Issue by spwhitton** [jwiegley/emacs-async#60]
1.6 is currently available from there.  Thanks!

**Comment by thierryvolpiatto** [comment]
You can use 1.7 by adding async to pinned-packages:

`(setq package-pinned-packages '((async . "melpa"))`

Ping @jwiegley 

Thanks.

**Comment by thierryvolpiatto** [comment]
@jwiegley now we are at version 1.8 ...

**Comment by jwiegley** [comment]
@thierryvolpiatto Is there any way I can put you in charge of this, so that it doesn't block on me?

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> @thierryvolpiatto Is there any way I can put you in charge of this, so
> that it doesn't block on me?

Well, if I have access to ELPA and you explain me how to synchronize, I
can do it if you want, I am in holidays actually, but as soon as I come
back, say in about two weeks, we can talk about it (I have intermittent
access to the internet here).
BTW I will release a new version when I come back because I made a lot
of improvements and bugfixes in dired-async.

-- 
Thierry

**Comment by spwhitton** [comment]
Are you definitely going to keep releasing on GitHub?

I can switch my packaging scripts over to base the Debian packaging of async.el on GitHub instead of GNU ELPA.  I only want to do that if it's definitely going to continue to be released here, though :)

**Comment by thierryvolpiatto** [comment]
Sean Whitton <notifications@github.com> writes:

> Are you definitely going to keep releasing on GitHub?

Yes, it is much more handy to maintain packages on github (at least for me).

> I can switch my packaging scripts over to base the Debian packaging of
> async.el on GitHub instead of GNU ELPA. I only want to do that if it's
> definitely going to continue to be released here, though :)

I think you can yes.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
@jwiegley now we are at 1.9...

**Comment by jwiegley** [comment]
@thierryvolpiatto I've been synchronizing to ELPA using git-subtree.  You're welcome to update it at any point.

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> @thierryvolpiatto I've been synchronizing to ELPA using git-subtree.

Thanks.

> You're welcome to update it at any point.

I have no write access to ELPA.

-- 
Thierry

**Comment by jwiegley** [comment]
@thierryvolpiatto I think that if you submit a request for membership to the Emacs project on Savannah, then I can make you a member and you'll have commit access to ELPA.

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> @thierryvolpiatto I think that if you submit a request for membership
> to the Emacs project on Savannah, then I can make you a member and
> you'll have commit access to ELPA.

If I do that and have access to ELPA, it is just to synchronize the
github repo and the ELPA one, in which case you will have to explain me the
procedure to achieve this.

NB: I do not want to work on ELPA, just synchronize github and ELPA when
needed.

BTW When I go on ELPA async homepage, it still indicate that async is at
1.6.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> @thierryvolpiatto I've been synchronizing to ELPA using git-subtree.

Ok, sorry for bad understanding of english, I understood you have
synchronized repos, but in fact you didn't do it recently.

> You're welcome to update it at any point.

I have cloned ELPA repo and merged async with github using git-subtree
fixing all conflicts happening because package.el developers insist to
provide infos (version etc...) in source files instead of in fixed
*pkg.el files...

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> @thierryvolpiatto I think that if you submit a request for membership
> to the Emacs project on Savannah, then I can make you a member and
> you'll have commit access to ELPA.

Done.

-- 
Thierry

**Comment by jwiegley** [comment]
It seems you have things underway now.  Let me know if any further instruction is needed, or if you need any other access.

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> It seems you have things underway now. Let me know if any further
> instruction is needed, or if you need any other access.

Thanks, ELPA async should now be up to date.

-- 
Thierry
