### ISSUE TITLE
not to work with org-caldav-sync

### ISSUE THREAD

**Issue by grauschnabel** [jwiegley/emacs-async#67]
Hi there,

I tried:

```
  (async-start
   ;; Sync caldav
   (org-caldav-sync)

   (lambda (result)
     (message "Caldav sync finished with %s" result)))

```
but it seems not to be async, emacs stops user input (25.1)

thanks for help

**Comment by thierryvolpiatto** [comment]
Martin <notifications@github.com> writes:

> Hi there,
>
> I tried:
>
>   (async-start
>    ;; Sync caldav
>    (org-caldav-sync)
>
>    (lambda (result)
>      (message "Caldav sync finished with %s" result)))
>
> but it seems not to be async, emacs stops user input (25.1)

I know nothing about `org-caldav-sync` but what I know is that if this
function is requiring a user interaction during its execution, it will
fail in `async-start` (of course).

--
Thierry

**Comment by grauschnabel** [comment]
Oh, yes of course... thanks.
