### ISSUE TITLE
Please consider to pull in the var `nsm-settings-file` for `smtpmail-async.el`

### ISSUE THREAD

**Issue by emelin** [jwiegley/emacs-async#75]
Hello,

please consider to pull in the var `nsm-settings-file` for `smtpmail-async.el`.

If this var is not set, sending fails since the enhanced network security (TLS/SSL certificate validity and the like) since Emacs 25.1.

All best,
emelin

**Comment by thierryvolpiatto** [comment]
emelin <notifications@github.com> writes:

> Hello,
>
> please consider to pull in the var nsm-settings-file for
> smtpmail-async.el.

What is nsm-setting-file ? I don't have this variable here on emacs-25.2
and it seems I can send email (this one) without problems throught
smtp-mail-async.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by emelin** [comment]
Well, `nsm` stands for `Network Security Manager` which I found kind of documented there:
    https://www.gnu.org/software/emacs/manual/html_node/emacs/Network-Security.html

If you like to send mail via a mail server asking for an SSL connection, but the SSL certificate appears to be 'untrusted' then (by default) `smtpmail-send-it` needs to be able to lookup its fingerprint as an exception in the file pointed to by the `nsm-settings-file`.

If you haven't got in this situation yet (like me for a long time ;-), you probably have never noticed `nsm`.

**Comment by thierryvolpiatto** [comment]
emelin <notifications@github.com> writes:

> Well, nsm stands for Network Security Manager which I found kind of documented there:
> https://www.gnu.org/software/emacs/manual/html_node/emacs/Network-Security.html

Thanks, got it.

Can you try if modifying `async-smtpmail-send-it` like this:

    @@ -64 +64 @@ It is called just before calling `smtpmail-send-it'.")
    -            "\\`\\(smtpmail\\|async-smtpmail\\|\\(user-\\)?mail\\)-\\|auth-sources\\|epg"
    +            "\\`\\(smtpmail\\|async-smtpmail\\|\\(user-\\)?mail\\)-\\|auth-sources\\|epg\\|nsm"

is working for you ?

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by emelin** [comment]
Yes, perfect! 
That's all it takes.
Thank you!
