### ISSUE TITLE
Please review makefile

### ISSUE THREAD

**Issue by thierryvolpiatto** [jwiegley/emacs-async#77]
@jwiegley I added a makefile.

The motivation is to install async in a standard location where other packages can find it when compiling.
Until now I guess nobody use really async.el itself due to this problem.
For example I wanted to use `async-let` in helm, ok no problem but as soon I ran make to compile helm, I ended up with errors complaining async where not found because it was installed in mu elisp directory which is not a standard location. See https://github.com/emacs-helm/helm/wiki#from-source.

Can you please review the makefile and correct if necessary ?

Thanks.

**Comment by jwiegley** [comment]
It looks good to me, @thierryvolpiatto. But I guess the real answer is: let's get this into Emacs.  All we need is to confirm copyright assignments for all contributions, and then we can commit it into 'master' core, towards Emacs 26.

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> It looks good to me, @thierryvolpiatto. But I guess the real answer
> is: let's get this into Emacs. All we need is to confirm copyright
> assignments for all contributions, and then we can commit it into
> 'master' core, towards Emacs 26.

Ah! yes, of course that would be great!

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
AFAICT when looking at https://github.com/jwiegley/emacs-async/graphs/contributors only @DarwinAwardWinner makes big changes but IIRC they have been reverted at the time because breaking async.el, the other changes are mostly README changes.

**Comment by DarwinAwardWinner** [comment]
In case any of my changes are still in, I've already signed the copyright assignment forms for Emacs.

**Comment by thierryvolpiatto** [comment]
Ryan C. Thompson <notifications@github.com> writes:

> In case any of my changes are still in, I've already signed the
> copyright assignment forms for Emacs.

Great! thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by jwiegley** [comment]
Then if we're good for assignment, do you think we're ready to push into master?  I'll probably open up a discussion for comments first.

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> Then if we're good for assignment, do you think we're ready to push
> into master?

Yes, will be a nice addition to emacs, I have released version 1.9.2,
the package seems stable.

> I'll probably open up a discussion for comments first.

Ok, thanks.


--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
@jwiegley when you open a discussion please Cc me as I generally don't follow emacs lists.
Thanks for reviewing makefile, closing now.
