### ISSUE TITLE
Missing tag for 1.9.2 release

### ISSUE THREAD

**Issue by spwhitton** [jwiegley/emacs-async#79]
Kindly add a git tag for the 1.9.2 release.

Thanks.

**Comment by jwiegley** [comment]
Added.

**Comment by thierryvolpiatto** [comment]
Sean Whitton <notifications@github.com> writes:

> Kindly add a git tag for the 1.9.2 release.

You mean on Elpa ?

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by spwhitton** [comment]
Thanks for the tag!

On Mon, Jun 19, 2017 at 12:28:55AM -0700, Thierry Volpiatto wrote:
> Sean Whitton <notifications@github.com> writes:
> 
> > Kindly add a git tag for the 1.9.2 release.
> 
> You mean on Elpa ?

No, I meant on GitHub.

I've switched Debian to track GNU ELPA for async, since it carries
various additional fixes not present in this repo.

-- 
Sean Whitton

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> Added.

I think I just forget to push 1.9.2 tag 2 months ago (but it was tagged
here), now the 1.9.2 tag you pushed is not at the same place than mine,
it includes a commit I was not sure about.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by jwiegley** [comment]
Which commit was that?

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> Which commit was that?

Was 6c9c3a2 but nevermind, the last commit I did it not too bad, I will
make another tag once I come back on it if needed.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
