### ISSUE TITLE
[Question] Is there any way for epa to loopback to parent emacs?

### ISSUE THREAD

**Issue by dieggsy** [jwiegley/emacs-async#88]
This may be nonsense, but I was wondering whether there's a way to get the pinentry prompt in the parent emacs rather than the async process one with `(setq epa-pinentry-mode 'loopback)`

**Comment by jwiegley** [comment]
At the moment, I don't think there's any backchannel communication from the subordinate Emacs until after it's done executing.

**Comment by dieggsy** [comment]
This is old, and it seems like there _isn't_ a way, so I'll close. Thanks.
