### ISSUE TITLE
async-byte-compile-log-file hardcode to "~/.emacs.d/async-bytecomp.log"

### ISSUE THREAD

**Issue by D4N** [jwiegley/emacs-async#95]
I have setup a CI for my personal init.el on gitlab and have noticed that the recent build has failed due to `/root/.emacs.d/async-bytecomp.log` not existing. The issue appears to be that the CI tests the init.el in a different directory then `~/.emacs.d/` and thus the directory for the byte compile log does not exist.

Would it be possible to define `async-byte-compile-log-file` in [async-bytecomp.el:54](https://github.com/jwiegley/emacs-async/blob/master/async-bytecomp.el#L54) to a value relative to the directory where the init.el file resides in?

I am not sure if this is possible or if it even makes sense (one of my installed packages is using emacs-async as a dependency, I can barely read elisp myself).

**Comment by thierryvolpiatto** [comment]
D4N <notifications@github.com> writes:

> I have setup a CI for my personal init.el on gitlab and have noticed
> that the recent build has failed due to
> /root/.emacs.d/async-bytecomp.log not existing. The issue appears to
> be that the CI tests the init.el in a different directory then
> ~/.emacs.d/ and thus the directory for the byte compile log does not
> exist.
>
> Would it be possible to define async-byte-compile-log-file in
> async-bytecomp.el:54 to a value relative to the directory where the
> init.el file resides in?

The init.el file should reside in `user-emacs-directory`, so is that
working for you:

    (defvar async-byte-compile-log-file (concat user-emacs-directory "async-bytecomp.log"))

--
Thierry

**Comment by D4N** [comment]
I have added the variable definition to my init.el and the CI build was fine this time. However, I am not sure if defining the variable in init.el overrides it for packages that are automatically pulled from (m)elpa. 

Also, I have seen that you have already pushed the change to the repo in 15bcbf6beae65d7606f0655711159ca56f050c6b. So that probably fixed the CI builds.

Thanks for the prompt fix!
